### PR TITLE
Introduce publication addresses #252

### PR DESCRIPTION
**Pull request by daddykotex**
Addresses: #252

### CODE REVIEW

**Comment by daddykotex** [comment]
The test is expected to fail. It seems that I cannot run tests in `FetchTests` I get errors like:

```
[error] Test coursierapi.test.FetchTests.simple failed: java.lang.RuntimeException: coursierapi.error.SimpleResolutionError$1: Error downloading com.chuusai:shapeless_2.13:2.3.3
[error]   not found: /Users/David.Francoeur/.ivy2/local/com.chuusai/shapeless_2.13/2.3.3/ivys/ivy.xml
[error]   No organization found, took 0.06 sec
[error]     at coursierapi.test.FetchTests.simple(FetchTests.java:28)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
[error] Caused by: coursierapi.error.SimpleResolutionError$1: Error downloading com.chuusai:shapeless_2.13:2.3.3
[error]   not found: /Users/David.Francoeur/.ivy2/local/com.chuusai/shapeless_2.13/2.3.3/ivys/ivy.xml
[error]   No organization found
[error]     at coursierapi.error.SimpleResolutionError.of(SimpleResolutionError.java:11)
[error]     at coursierapi.shaded.coursier.internal.api.ApiHelper$.simpleResError(ApiHelper.scala:338)
[error]     at coursierapi.shaded.coursier.internal.api.ApiHelper$.doFetch(ApiHelper.scala:382)
[error]     at coursierapi.shaded.coursier.internal.api.ApiHelper.doFetch(ApiHelper.scala)
[error]     at coursierapi.Fetch.fetchResult(Fetch.java:244)
[error]     at coursierapi.test.FetchTests.simple(FetchTests.java:26)
[error]     ... 54 more

```

I'm not sure why it only looks up in local and not on maven central.

**Comment by daddykotex** [comment]
Ahh the failures are related to my changes

**Comment by daddykotex** [comment]
I can test on my fork. I will reopen when I get a working build...

**Comment by alexarchambault** [comment]
Looking forward to it, then!

**Comment by daddykotex** [comment]
I can't run `interface-tests` locally, I don't know why, when I run `interface-test/test` it does nothing...

```
sbt:coursier-interface> show Test/sources
[info] interface / Test / sources
[info]  Vector(/Users/David.Francoeur/workspace/dev/coursier-interface/interface/src/test/scala/coursierapi/DependencyTests.scala, /Users/David.Francoeur/workspace/dev/coursier-interface/interface/src/test/scala/coursierapi/ResolutionParamsTests.scala, /Users/David.Francoeur/workspace/dev/coursier-interface/interface/src/test/scala/coursierapi/RepositoryTests.scala)
[info] interface-svm-subs / Test / sources
[info]  Vector()
[info] interpolators / Test / sources
[info]  Vector(/Users/David.Francoeur/workspace/dev/coursier-interface/interpolators/src/test/scala/coursierapi/InterpolatorTests.scala)
[info] interface-test / Test / sources
[info]  Vector(/Users/David.Francoeur/workspace/dev/coursier-interface/interface-test/src/test/java/coursierapi/test/CompleteTests.java, /Users/David.Francoeur/workspace/dev/coursier-interface/interface-test/src/test/java/coursierapi/test/JvmManagerTests.java, /Users/David.Francoeur/workspace/dev/coursier-interface/interface-test/src/test/java/coursierapi/test/VersionsTests.java, /Users/David.Francoeur/workspace/dev/coursier-interface/interface-test/src/test/java/coursierapi/test/FetchTests.java)
[info] Test / sources
[info]  Vector()
[success] Total time: 0 s, completed Jun. 2, 2022, 9:47:15 a.m.
sbt:coursier-interface> interface-test / Test / test
[success] Total time: 1 s, completed Jun. 2, 2022, 9:47:32 a.m.
sbt:coursier-interface> 
```

**Comment by daddykotex** [comment]
see https://github.com/coursier/interface/pull/254

**Pull request closed without merging**
